apiVersion: v1
kind: Service
metadata:
  name: headless-service
  namespace: mynamespace
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: headless-service
  namespace: mynamespace
subsets:
  - addresses:
      - ip: 240.0.0.1
    ports:
      - port: 8001
