apiVersin: v1
kind: PersistantVolume
metadata:
  name: pv-demo
spec:
  storageClassName: standard
  accessMode:
  - ReadWriteOnce
    capacity: 1Gi
    AwsElasticBlockStore
      VolumeID: vol-0e89451c9071f37ea
      fsType: ext4 
     ---
     apiVersion: v1
     kind: PersistantVolumeClaim
     metadata:
       name: pvc-demo
     spec:
       accessmode: ReadwriteOnce
       resource:
         request:
           storage: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  containers:
  - name: pv-pod
    image: nginx
    volumeMounts:
    - mountPath: "/var/persistent"
      name: pv-pod
  volumes:
    - name: pod-pv
      persistantVolumeClaim:
        claimName: pvc-demo
