apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-pod
  labels:
    app: nginx
    types: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
